name: "Dev Terraform Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:

    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Terraform setup step
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
            
      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/dev
        
      - name: Configure azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: backendrg
          container_name: backendcontainer
          storage_account_name: backendstorge

      # ✅ Init required before validate
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: environments/dev
            
      - name: Terraform Validate
        run: terraform validate -no-color
        working-directory: environments/dev     

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3

        
  terraform-apply:    

    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Terraform setup step again
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
          
      - name: Configure azurerm backend
        uses: ahmedig/terraform-azurerm-backend@v4
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          resource_group_name: backendrg
          container_name: backendcontainer
          storage_account_name: backendstorge

      # ✅ Init again before plan
      - name: Terraform Init
        run: terraform init -input=false
        working-directory: environments/dev

      - name: Terraform Plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/dev
